export const ROUTES = {
    DASHBOARD: '/dashboard',
    LOGIN: '/login',
    PROFILE: '/profile',
    LIST_TAGIHAN: '/list-tagihan',
    LIST_PEMBAYARAN: '/list-pembayaran',
    LIST_PELAPORAN: '/list-pelaporan',
    PELANGGAN: '/master/pelanggan',
    BIAYA: '/master/biaya',
    PEGAWAI: '/master/pegawai',
    RESET_PASSWORD: '/reset-password',
    REKENING: '/master/rekening',
    CHANGE_PASSWORD: '/change-password',
    REPORT: '/report',
    KEBIJAKAN: '/kebijakanprivasi',
};
